name: My Wishlist

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install --save-dev --force
    - run: npm audit --omit=dev || true
    - run: npm run lint || true
    - run: npx ng build --configuration production
    - uses: actions/upload-artifact@v3
      with:
        name: my-wishlist-release
        path: dist/wishlist
